#!/bin/bash

input_file="$1"
chosen_folder="$2"

output_dir="word_images"
mkdir -p "$output_dir"

# Split text into words and output each word to an image
counter=0
for word in $(cat "$input_file"); do
((counter++))
image_file="${output_dir}/word_${counter}.png"

convert -size 250x100 xc:none \
	-gravity center \
	-fill black \
	-pointsize 68 \
	-weight Bold \
	-annotate +0+0 "$word" \
	"$image_file"
done

mv "$output_dir" "$chosen_folder"
